apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: devops-lab
      defaultBucket: multicloud_cost
      tlsSkipVerify: true
    secureJsonData:
      token: change-me
