from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

"""
This module defines the core data schemas used throughout the Multi-Cloud Cost Optimization pipeline.
These dataclasses ensure strict typing and standardized data structures for cost records, 
recommendations, and alerts, regardless of which cloud provider generated them.
"""


@dataclass(frozen=True)
class CostRecord:
    """
    Represents a unified cost record for a specific cloud service over a specific time period.
    This schema abstracts away provider-specific details into a common format.
    """
    cloud: str
    service: str
    account_id: str
    currency: str
    amount: float
    period_start: datetime
    period_end: datetime
    region: str = "global"
    utilization_pct: Optional[float] = None
    tax_amount: float = 0.0 # Added to handle tax implications (like Rule 14 notional costs)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def alert_key(self) -> str:
        """
        Generates a unique key for alert deduplication based on the cloud, account, service, and day.
        
        Returns:
            str: A formatted deduplication key (e.g., 'aws:12345:EC2:2023-10-01').
        """
        day = self.period_start.strftime("%Y-%m-%d")
        return f"{self.cloud}:{self.account_id}:{self.service}:{day}"


@dataclass(frozen=True)
class Recommendation:
    """
    Represents an actionable rightsizing or cost-saving recommendation generated by the engine.
    """
    cloud: str
    service: str
    resource_id: str
    severity: str
    title: str
    description: str
    estimated_monthly_savings: float
    created_at: datetime
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AlertEvent:
    """
    Represents an anomaly or cost spike alert intended for delivery to external channels (e.g., Slack).
    """
    channel: str
    title: str
    body: str
    dedupe_key: str
    records: List[CostRecord]
    created_at: datetime
